load("//bazel:build_system.bzl", "carrot_cc_library")

carrot_cc_library(
    name = "signal_monitor_lib",
    srcs = ["signal_monitor.cc"],
    hdrs = ["signal_monitor.hh"],
    visibility = ["//visibility:public"],
    deps = [
        "//include/carrot/event:dispatcher_interface",
        "//include/carrot/event:io_object_interface",
        "//src/core/logging:log_lib",
    ],
)

carrot_cc_library(
    name = "node_directory_lib",
    srcs = ["node_directory.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//include/carrot/common:node_directory_lib",
    ],
)

carrot_cc_library(
    name = "wire_protocol_lib",
    srcs = ["wire_protocol.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//include/carrot/common:types_lib",
        "//include/carrot/common:wire_protocol_lib",
        "@msgpack",
    ],
)

carrot_cc_library(
    name = "connection_pool_lib",
    srcs = ["connection_pool.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//include/carrot/common:connection_pool_lib",
    ],
)
